### ISSUE TITLE
The question about cuckoo hash

### ISSUE THREAD

**Issue by qianyukun** [encryptogroup/PSI#2]
I have found a question that when the participants Alice and Bob have exactly the same sets information X, the intersection is not equal to X. Especially when the set size is large, the number of intersections calculated by the PSI protocol is far less than that computed by the plaintext. Even though I set the number of hash bins of Alice to be 166*n1 (suppose n1 is set size of Alice) when using cuckoo hash. I am confused why the result is inaccurate.

**Comment by JiajieZhang-Georgia** [comment]
Hi @qianyukun 
Which protocol did you use in your experiment?
I'm stuck in the server-aided one, 
I'm wondering if I can get some help from you.
Thank you.

**Comment by yanzifan021** [comment]
Hi @JiajieZhang-Georgia 
Did you manage to run the server aid protocol?
I am stuck in the server-aid protocol also

**Comment by aurora1994** [comment]
Hi @qianyukun
I have the exactly same issue as you. Did you find the way to solve it?
