### ISSUE TITLE
make: *** [Makefile:70：src/util/ot/kk-ot-extension.o]  Error 1

### ISSUE THREAD

**Issue by MiJingGitID12138** [encryptogroup/PSI#5]
When I try to make it, there is an error. I don't konw the reason for this error.
System: Ubuntu 18

Details are as follows: 

$ make
g++ src/util/ot/kk-ot-extension.cpp -g3 -O2  -g3 -ggdb  -c -I..  -I/usr/include/glib-2.0/ -I/usr/lib/x86_64-linux-gnu/glib-2.0/include `pkg-config --cflags glib-2.0` -lgmp -lgmpxx -lpthread  -L /usr/lib  -lssl -lcrypto -lglib-2.0 `pkg-config --libs glib-2.0`   -o src/util/ot/kk-ot-extension.o
In file included from /usr/include/c++/8/cmath:45,
                 from /usr/include/c++/8/math.h:36,
                 from src/util/ot/../cbitvector.h:14,
                 from src/util/ot/kk-ot-extension.h:11,
                 from src/util/ot/kk-ot-extension.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls-narrow.h:24:20: error: conflicting declaration of C function ‘float fadd(double, double)’
 __MATHCALL_NARROW (__MATHCALL_NAME (add), __MATHCALL_REDIR_NAME (add), 2);
                    ^~~~~~~~~~~~~~~
In file included from src/util/ot/../crypto/../../externals/miracl_lib/big.h:103,
                 from src/util/ot/../crypto/../../externals/miracl_lib/ecn.h:56,
                 from src/util/ot/../crypto/ecc-pk-crypto.h:13,
                 from src/util/ot/../crypto/crypto.h:20,
                 from src/util/ot/../cbitvector.h:11,
                 from src/util/ot/kk-ot-extension.h:11,
                 from src/util/ot/kk-ot-extension.cpp:1:
src/util/ot/../crypto/../../externals/miracl_lib/miracl.h:1350:14: note: previous declaration ‘void fadd(flash, flash, flash)’
 extern void  fadd(_MIPT_ flash,flash,flash);
              ^~~~
In file included from /usr/include/c++/8/cmath:45,
                 from /usr/include/c++/8/math.h:36,
                 from src/util/ot/../cbitvector.h:14,
                 from src/util/ot/kk-ot-extension.h:11,
                 from src/util/ot/kk-ot-extension.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls-narrow.h:27:20: error: conflicting declaration of C function ‘float fdiv(double, double)’
 __MATHCALL_NARROW (__MATHCALL_NAME (div), __MATHCALL_REDIR_NAME (div), 2);
                    ^~~~~~~~~~~~~~~
In file included from src/util/ot/../crypto/../../externals/miracl_lib/big.h:103,
                 from src/util/ot/../crypto/../../externals/miracl_lib/ecn.h:56,
                 from src/util/ot/../crypto/ecc-pk-crypto.h:13,
                 from src/util/ot/../crypto/crypto.h:20,
                 from src/util/ot/../cbitvector.h:11,
                 from src/util/ot/kk-ot-extension.h:11,
                 from src/util/ot/kk-ot-extension.cpp:1:
src/util/ot/../crypto/../../externals/miracl_lib/miracl.h:1349:14: note: previous declaration ‘void fdiv(flash, flash, flash)’
 extern void  fdiv(_MIPT_ flash,flash,flash);
              ^~~~
In file included from /usr/include/c++/8/cmath:45,
                 from /usr/include/c++/8/math.h:36,
                 from src/util/ot/../cbitvector.h:14,
                 from src/util/ot/kk-ot-extension.h:11,
                 from src/util/ot/kk-ot-extension.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls-narrow.h:30:20: error: conflicting declaration of C function ‘float fmul(double, double)’
 __MATHCALL_NARROW (__MATHCALL_NAME (mul), __MATHCALL_REDIR_NAME (mul), 2);
                    ^~~~~~~~~~~~~~~
In file included from src/util/ot/../crypto/../../externals/miracl_lib/big.h:103,
                 from src/util/ot/../crypto/../../externals/miracl_lib/ecn.h:56,
                 from src/util/ot/../crypto/ecc-pk-crypto.h:13,
                 from src/util/ot/../crypto/crypto.h:20,
                 from src/util/ot/../cbitvector.h:11,
                 from src/util/ot/kk-ot-extension.h:11,
                 from src/util/ot/kk-ot-extension.cpp:1:
src/util/ot/../crypto/../../externals/miracl_lib/miracl.h:1348:14: note: previous declaration ‘void fmul(flash, flash, flash)’
 extern void  fmul(_MIPT_ flash,flash,flash);
              ^~~~
In file included from /usr/include/c++/8/cmath:45,
                 from /usr/include/c++/8/math.h:36,
                 from src/util/ot/../cbitvector.h:14,
                 from src/util/ot/kk-ot-extension.h:11,
                 from src/util/ot/kk-ot-extension.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls-narrow.h:33:20: error: conflicting declaration of C function ‘float fsub(double, double)’
 __MATHCALL_NARROW (__MATHCALL_NAME (sub), __MATHCALL_REDIR_NAME (sub), 2);
                    ^~~~~~~~~~~~~~~
In file included from src/util/ot/../crypto/../../externals/miracl_lib/big.h:103,
                 from src/util/ot/../crypto/../../externals/miracl_lib/ecn.h:56,
                 from src/util/ot/../crypto/ecc-pk-crypto.h:13,
                 from src/util/ot/../crypto/crypto.h:20,
                 from src/util/ot/../cbitvector.h:11,
                 from src/util/ot/kk-ot-extension.h:11,
                 from src/util/ot/kk-ot-extension.cpp:1:
src/util/ot/../crypto/../../externals/miracl_lib/miracl.h:1351:14: note: previous declaration ‘void fsub(flash, flash, flash)’
 extern void  fsub(_MIPT_ flash,flash,flash);
              ^~~~
make: *** [Makefile:70：src/util/ot/kk-ot-extension.o] Error 1

**Comment by Oleksandr-Tkachenko** [comment]
Hi @MiJingGitID12138, 

this should be fixed in e5057094ec8bc0469fc1e207ab49d08132dfdabc. Please try to build again using the latest commit (i.e., run ``git pull`` beforehand). 

Please tell us afterwards if this fixes your issue.

Thank you to @lenerd for fixing this!
